load("@com_bluecore_rules_pyz//rules_python_zip:rules_python_zip.bzl", "pyz_binary", "pyz_test")

pyz_test(
    name="test",
    srcs=["test.py"],
)

pyz_binary(
    name="binary",
    srcs=["binary.py"],
)
