git_repository(
    name = "com_bluecore_rules_pyz",
    commit = "REPLACECOMMIT",
    remote = "REPLACEREMOTE",
)
load("@com_bluecore_rules_pyz//rules_python_zip:rules_python_zip.bzl", "pyz_repositories")
pyz_repositories()
